### ISSUE TITLE
An unhappend problem

### ISSUE THREAD

**Issue by lxj15398019970** [bytedance/sonic#234] opened 2022-05-26 03:27 UTC
traceback: unexpected SPWRITE function github.com/bytedance/sonic/internal/native/avx2.__native_entry__
fatal error: traceback

runtime stack:
runtime.throw({0x12ef91c, 0x1de4260})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.gentraceback(0x7fc3972db850, 0x1580, 0xc01949fba0, 0xc0eb5aa4e0, 0x0, 0x0, 0x7fffffff, 0x7fc385ff7460, 0x400000002, 0x0)
	/usr/local/go/src/runtime/traceback.go:238 +0x19c5
runtime.addOneOpenDeferFrame.func1()
	/usr/local/go/src/runtime/panic.go:751 +0x6b
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:383 +0x49

goroutine 6113840 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc000367488 sp=0xc000367480 pc=0x4d08a0
runtime.addOneOpenDeferFrame(0xc8, 0x1fffffff, 0x47012d)
	/usr/local/go/src/runtime/panic.go:750 +0x77 fp=0xc0003674c8 sp=0xc000367488 pc=0x49e537
panic({0x11df0a0, 0x1d84b40})
	/usr/local/go/src/runtime/panic.go:998 +0x114 fp=0xc000367588 sp=0xc0003674c8 pc=0x49f354
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:221
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:735 +0x327 fp=0xc0003675d8 sp=0xc000367588 pc=0x4b5c47
github.com/bytedance/sonic/internal/native/avx2.__native_entry__()
	/data/gopath/pkg/mod/github.com/bytedance/sonic@v1.1.1/internal/native/avx2/native_amd64.s:1618 +0x1565 fp=0xc0003675e0 sp=0xc0003675d8 pc=0x910925
created by gateway/handler.selectAppItemsBidResponse
	/home/ubuntu/remotejenkins/workspace/Gears_Docker_tar2/dsp-gateway/src/handler/dispatcher-handler.go:114 +0x2af

**Comment by lxj15398019970** [comment] 2022-05-26 03:27
gc 147 @1431.292s 0%: 0.12+94+0.040 ms clock, 0.48+31/94/43+0.16 ms cpu, 3981->3998->2035 MB, 4083 MB goal, 4 P
gc 148 @1442.209s 0%: 0.18+116+0.003 ms clock, 0.72+35/113/40+0.015 ms cpu, 3969->3991->2040 MB, 4070 MB goal, 4 P
gc 149 @1451.931s 0%: 0.18+102+0.053 ms clock, 0.74+36/98/30+0.21 ms cpu, 3979->4000->2067 MB, 4081 MB goal, 4 P
gc 150 @1462.831s 0%: 0.25+89+0.057 ms clock, 1.0+33/88/61+0.23 ms cpu, 4031->4055->2042 MB, 4134 MB goal, 4 P
gc 151 @1473.339s 0%: 0.12+96+0.072 ms clock, 0.50+33/96/62+0.29 ms cpu, 3982->3999->2038 MB, 4085 MB goal, 4 P
2022-05-26T02:33:32Z RotateLog>name>/pdata1/log/dspgateway/ali-tky107-gatewaydocker-135-107/csv_bidrequest_%Y%M%D%H_%m%s.log,Hour>2,hourly_opendate>2,Day>26,daily_opendate>26
2022-05-26T02:33:32Z fileRotate>name>/pdata1/log/dspgateway/ali-tky107-gatewaydocker-135-107/csv_bidrequest_%Y%M%D%H_%m%s.log,Hour>2,hourly_opendate>2,Day>26,daily_opendate>26,fileName>/pdata1/log/dspgateway/ali-tky107-gatewaydocker-135-107/csv_bidrequest_2022052602_3333.log
gc 152 @1484.252s 0%: 0.20+109+0.025 ms clock, 0.82+57/108/27+0.10 ms cpu, 3975->3997->2043 MB, 4077 MB goal, 4 P
gc 153 @1495.183s 0%: 0.16+107+0.062 ms clock, 0.67+41/104/42+0.25 ms cpu, 3985->4005->2044 MB, 4087 MB goal, 4 P
gc 154 @1506.133s 0%: 0.15+103+0.005 ms clock, 0.60+69/101/0+0.020 ms cpu, 3986->4009->2048 MB, 4088 MB goal, 4 P
gc 155 @1514.903s 0%: 0.20+84+0.058 ms clock, 0.81+20/83/61+0.23 ms cpu, 3995->4008->2068 MB, 4097 MB goal, 4 P
gc 156 @1526.038s 0%: 0.14+89+0.046 ms clock, 0.59+55/89/35+0.18 ms cpu, 4033->4057->2053 MB, 4136 MB goal, 4 P
gc 157 @1536.910s 0%: 0.14+103+0.074 ms clock, 0.59+22/97/49+0.29 ms cpu, 4004->4026->2059 MB, 4107 MB goal, 4 P
gc 158 @1548.086s 0%: 0.14+105+0.003 ms clock, 0.57+38/104/35+0.013 ms cpu, 4015->4037->2065 MB, 4118 MB goal, 4 P
gc 159 @1559.141s 0%: 0.24+99+0.052 ms clock, 0.99+35/99/62+0.21 ms cpu, 4027->4047->2056 MB, 4130 MB goal, 4 P
2022-05-26T02:34:57Z RotateLog>name>/pdata1/log/dspgateway/ali-tky107-gatewaydocker-135-107/csv_bidrequest_%Y%M%D%H_%m%s.log,Hour>2,hourly_opendate>2,Day>26,daily_opendate>26
2022-05-26T02:34:57Z fileRotate>name>/pdata1/log/dspgateway/ali-tky107-gatewaydocker-135-107/csv_bidrequest_%Y%M%D%H_%m%s.log,Hour>2,hourly_opendate>2,Day>26,daily_opendate>26,fileName>/pdata1/log/dspgateway/ali-tky107-gatewaydocker-135-107/csv_bidrequest_2022052602_3458.log
gc 160 @1569.179s 0%: 0.29+126+0.022 ms clock, 1.1+134/114/0+0.088 ms cpu, 4011->4036->2096 MB, 4113 MB goal, 4 P
gc 161 @1579.658s 0%: 0.17+92+0.004 ms clock, 0.69+16/92/78+0.016 ms cpu, 4088->4105->2068 MB, 4193 MB goal, 4 P
traceback: unexpected SPWRITE function github.com/bytedance/sonic/internal/native/avx2.__native_entry__
fatal error: traceback

runtime stack:
runtime.throw({0x12ef91c, 0x1de4260})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.gentraceback(0x7fc3972db850, 0x1580, 0xc01949fba0, 0xc0eb5aa4e0, 0x0, 0x0, 0x7fffffff, 0x7fc385ff7460, 0x400000002, 0x0)
	/usr/local/go/src/runtime/traceback.go:238 +0x19c5
runtime.addOneOpenDeferFrame.func1()
	/usr/local/go/src/runtime/panic.go:751 +0x6b
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:383 +0x49

goroutine 6113840 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc000367488 sp=0xc000367480 pc=0x4d08a0
runtime.addOneOpenDeferFrame(0xc8, 0x1fffffff, 0x47012d)
	/usr/local/go/src/runtime/panic.go:750 +0x77 fp=0xc0003674c8 sp=0xc000367488 pc=0x49e537
panic({0x11df0a0, 0x1d84b40})
	/usr/local/go/src/runtime/panic.go:998 +0x114 fp=0xc000367588 sp=0xc0003674c8 pc=0x49f354
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:221
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:735 +0x327 fp=0xc0003675d8 sp=0xc000367588 pc=0x4b5c47
github.com/bytedance/sonic/internal/native/avx2.__native_entry__()
	/data/gopath/pkg/mod/github.com/bytedance/sonic@v1.1.1/internal/native/avx2/native_amd64.s:1618 +0x1565 fp=0xc0003675e0 sp=0xc0003675d8 pc=0x910925
created by gateway/handler.selectAppItemsBidResponse
	/home/ubuntu/remotejenkins/workspace/Gears_Docker_tar2/dsp-gateway/src/handler/dispatcher-handler.go:114 +0x2af

goroutine 1 [runnable]:
syscall.Syscall6(0x120, 0x65, 0xc0dc7ff988, 0xc0dc7ff974, 0x80800, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:43 +0x5
syscall.accept4(0xc0dc7ff988, 0x2000, 0x0, 0x100000100)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1405 +0x4e
syscall.Accept4(0x197565d61ab, 0xc0dc7ffa70)
	/usr/local/go/src/syscall/syscall_linux.go:575 +0x6d
internal/poll.accept(0xc01716b000)
	/usr/local/go/src/internal/poll/sock_cloexec.go:18 +0x2e
internal/poll.(*FD).Accept(0xc01716b000)
	/usr/local/go/src/internal/poll/fd_unix.go:393 +0x1be
net.(*netFD).accept(0xc01716b000)
	/usr/local/go/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc0166d5d88)
	/usr/local/go/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc0166d5d88)
	/usr/local/go/src/net/tcpsock.go:262 +0x3d
github.com/valyala/fasthttp.acceptConn(0xc01709aa00, {0x146fd80, 0xc0166d5d88}, 0xc0dc7ffde0)
	/data/gopath/pkg/mod/github.com/valyala/fasthttp@v1.5.0/server.go:1676 +0x62
github.com/valyala/fasthttp.(*Server).Serve(0xc01709aa00, {0x146fd80, 0xc0166d5d88})
	/data/gopath/pkg/mod/github.com/valyala/fasthttp@v1.5.0/server.go:1594 +0x405
github.com/valyala/fasthttp.(*Server).ListenAndServe(0xc01709aa00, {0x12e7c77, 0x41})
	/data/gopath/pkg/mod/github.com/valyala/fasthttp@v1.5.0/server.go:1386 +0xa5
gateway/handler.startFastHttpServer()
	/home/ubuntu/remotejenkins/workspace/Gears_Docker_tar2/dsp-gateway/src/handler/handler-server.go:238 +0x1c8
gateway/handler.StartServer()
	/home/ubuntu/remotejenkins/workspace/Gears_Docker_tar2/dsp-gateway/src/handler/handler-server.go:137 +0x32c
main.main()

**Comment by chenzhuoyu** [comment] 2022-05-26 15:12
Duplicate of #236

**Closed by chenzhuoyu** 2022-05-26 15:12 UTC
Labels: duplicate
