### ISSUE TITLE
panic: unexpected fault address 0xc0c1800000 fatal error

### ISSUE THREAD

**Issue by intfish123** [bytedance/sonic#507] opened 2023-08-17 09:11 UTC
```
unexpected fault address 0xc0c1800000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc0c1800000 pc=0xb80610]

goroutine 184 [running]:
runtime.throw({0xfaf15f?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc0005dab08 sp=0xc0005daad8 pc=0x44957d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:842 +0x2c5 fp=0xc0005dab58 sp=0xc0005dab08 pc=0x45f2e5
runtime: g 184: unexpected return pc for github.com/bytedance/sonic/internal/native/avx.__native_entry__ called from 0x1ffb
stack: frame={sp:0xc0005dab58, fp:0xc0005dab60} stack=[0xc0005d8000,0xc0005dc000)
0x000000c0005daa58:  0x000000000044b0b2 <runtime.gwrite+0x00000000000000f2>  0x000000000113cb00 
0x000000c0005daa68:  0x0000000000000001  0x0000000000000001 
0x000000c0005daa78:  0x000000c0005daaec  0x000000000000000c 
0x000000c0005daa88:  0x000000000047886e <runtime.systemstack+0x000000000000002e>  0x00000000004498cc <runtime.fatalthrow+0x000000000000006c> 
0x000000c0005daa98:  0x000000c0005daaa8  0x000000c000803040 
0x000000c0005daaa8:  0x0000000000449900 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000c000803040 
0x000000c0005daab8:  0x000000000044957d <runtime.throw+0x000000000000005d>  0x000000c0005daad8 
0x000000c0005daac8:  0x000000c0005daaf8  0x000000000044957d <runtime.throw+0x000000000000005d> 
0x000000c0005daad8:  0x000000c0005daae0  0x00000000004495a0 <runtime.throw.func1+0x0000000000000000> 
0x000000c0005daae8:  0x0000000000faf15f  0x0000000000000005 
0x000000c0005daaf8:  0x000000c0005dab48  0x000000000045f2e5 <runtime.sigpanic+0x00000000000002c5> 
0x000000c0005dab08:  0x0000000000faf15f  0x0000000000000000 
0x000000c0005dab18:  0x0000000000203030  0x0000000000203030 
0x000000c0005dab28:  0x000000c0c1800000  0x000000c0005daba8 
0x000000c0005dab38:  0x000000000041edbf <runtime.mallocgc+0x000000000000069f>  0xffffffffffffffff 
0x000000c0005dab48:  0x000000c0005dab70  0x0000000000b80610 <github.com/bytedance/sonic/internal/native/avx.__native_entry__+0x00000000000051b0> 
0x000000c0005dab58: <0x0000000000001ffb >0x000000c0c17ffffb 
0x000000c0005dab68:  0x0000000000001ffe  0x000000c0005dabd0 
0x000000c0005dab78:  0x0000000000b7e657 <github.com/bytedance/sonic/internal/native/avx.__native_entry__+0x00000000000031f7>  0x000000c0c17fe000 
0x000000c0005dab88:  0x0000000000001ffe  0x000000c0c17f7ed0 
0x000000c0005dab98:  0x000000c0005dac58  0x0000000000001ffb 
0x000000c0005daba8:  0x000000c0c170d3e0  0x0000000000001ffe 
0x000000c0005dabb8:  0x000000c09fd8c008  0x000000c000803040 
0x000000c0005dabc8:  0x000000c0c17eada8  0x000000c0c17fe000 
0x000000c0005dabd8:  0x00007f35b086c1a8 <decode_value+0x00000000000001a8>  0x000000c0c17fffc8 
0x000000c0005dabe8:  0x0000000000000018  0x0000000000000110 
0x000000c0005dabf8:  0x0000000000f22c20  0x000000c0c17ebc01 
0x000000c0005dac08:  0x000000c0c17ebca8  0x000000c0005dac40 
0x000000c0005dac18:  0x0000000000425366 <runtime.growWork_faststr+0x0000000000000066>  0x000000c09fd8c008 
0x000000c0005dac28:  0x000000c0c17eb248  0x000000c0c17fe000 
0x000000c0005dac38:  0x0000000000001ffe  0xffffffffffffffff 
0x000000c0005dac48:  0x0000000000424bd7 <runtime.mapassign_faststr+0x0000000000000077>  0x0000000000000002 
0x000000c0005dac58:  0x000000c09fd84000 
github.com/bytedance/sonic/internal/native/avx.__native_entry__()
	/go/pkg/mod/github.com/bytedance/sonic@v1.9.2/internal/native/avx/native_amd64.s:6069 +0x51b0 fp=0xc0005dab60 sp=0xc0005dab58 pc=0xb80610
created by gosinker/output.(*ClickhouseNode).StartWriteData
	/build/output/clickhouse.go:205 +0x185
```

**Comment by liuq19** [comment] 2023-08-18 05:25
thanks, it seems some problem in `skip_number`, we will investigate it

**Comment by intfish123** [comment] 2023-08-18 08:30
It's just happend occasionally.

**Comment by intfish123** [comment] 2023-08-23 09:56
How about the progress? @liuq19

**Comment by liuq19** [comment] 2023-08-24 06:27
This may be caused by data race, if it is occasionally. We will try to reproduce the problem ~

**Comment by liuq19** [comment] 2023-09-11 12:21
Fixed in https://github.com/bytedance/sonic/releases/tag/v1.10.1

**Closed by liuq19** 2023-09-11 12:21 UTC
