### ISSUE TITLE
Error after update go1.19

### ISSUE THREAD

**Issue by centratelemedia** [bytedance/sonic#276] opened 2022-08-05 02:36 UTC
C:\Users\Admin\go\pkg\mod\github.com\bytedance\sonic@v1.3.4\internal\loader\funcdata.go:79:26: undefined: _ModuleData      
C:\Users\Admin\go\pkg\mod\github.com\bytedance\sonic@v1.3.4\internal\loader\funcdata_invalid.go:23:6: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18") (no value) used as value
C:\Users\Admin\go\pkg\mod\github.com\bytedance\sonic@v1.3.4\internal\loader\loader_windows.go:49:50: too many arguments in 
call to registerFunction
        have (string, uintptr, uintptr, int, int, uintptr, uintptr, uintptr)
        want (string, uintptr, int, int, uintptr)

**Comment by ii64** [comment] 2022-08-05 02:48
Duplicate of #272, PR #275

**Closed** 2022-08-05 04:07 UTC
